name: CI for Zakladki React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-build-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # You can adjust the Node.js version based on your project requirements

    - name: Install dependencies
      run: npm install

    - name: Lint the code
      run: npm run lint

    - name: Build the app
      run: npm run build

    - name: Upload production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/

  test:
    runs-on: ubuntu-latest
    needs: install-build-lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    # Add testing step here if applicable
    # Example:
    # - name: Run tests
    #   run: npm run test
